import { Injectable } from '@angular/core';
import { Flag } from '../interfaces/flag';

@Injectable({
  providedIn: 'root',
})
export class FlagsService {
  getFlags(): Flag[] {
    return [
      {
        id: 1,
        name: 'uk',
        title: 'United Kingdom',
        alt: 'United Kingdom',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 2,
        name: 'jp',
        title: 'Japan',
        alt: 'Japan',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 3,
        name: 'br',
        title: 'Brazil',
        alt: 'Brazil',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 4,
        name: 'au-hk',
        title: 'Australia-Hong Kong',
        alt: 'Australia-Hong Kong',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 5,
        name: 'us',
        title: 'United States',
        alt: 'United States',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 6,
        name: '',
        title: '',
        alt: '',
        classBoth: '',
        classHuge: ' --huge',
        isBack: false,
        isInfo: true,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 7,
        name: 'nl',
        title: 'Netherlands',
        alt: 'Netherlands',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 8,
        name: 'fr-es',
        title: 'France-Spain',
        alt: 'France-Spain',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-3',
      },
      {
        id: 9,
        name: 'mx',
        title: 'Mexico',
        alt: 'Mexico',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 10,
        name: 'in',
        title: 'India',
        alt: 'India',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 11,
        name: 'de-be',
        title: 'Germany-Belgium',
        alt: 'Germany-Belgium',
        classBoth: ' both-span',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-5',
      },
      {
        id: 12,
        name: 'it',
        title: 'Italy',
        alt: 'Italy',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 13,
        name: 'ca-id',
        title: 'Canada-Indonesia',
        alt: 'Canada-Indonesia',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-10',
      },
      {
        id: 14,
        name: 'ru',
        title: 'Russia',
        alt: 'Russia',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 15,
        name: 'ua',
        title: 'Ukraine',
        alt: 'Ukraine',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 16,
        name: 'in',
        title: 'India',
        alt: 'India',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 17,
        name: 'cn',
        title: 'China',
        alt: 'China',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 18,
        name: 'kr',
        title: 'South Korea',
        alt: 'South Korea',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 19,
        name: 'co',
        title: 'Colombia',
        alt: 'Colombia',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 20,
        name: 'pl',
        title: 'Poland',
        alt: 'Poland',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 21,
        name: 'se',
        title: 'Sweden',
        alt: 'Sweden',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 22,
        name: 'ph',
        title: 'Philippines',
        alt: 'Philippines',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 23,
        name: 'pt',
        title: 'Portugal',
        alt: 'Portugal',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 24,
        name: 'sg',
        title: 'Singapore',
        alt: 'Singapore',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 25,
        name: 'vd-th',
        title: 'Vietnam-Thailand',
        alt: 'Vietnam-Thailand',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-15',
      },
      {
        id: 26,
        name: 'ar',
        title: 'Argentina',
        alt: 'Argentina',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 27,
        name: 'ch',
        title: 'Switzerland',
        alt: 'Switzerland',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 28,
        name: 'tr',
        title: 'Turkey',
        alt: 'Turkey',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 29,
        name: 'tw',
        title: 'Taiwan',
        alt: 'Taiwan',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
    ];
  }
  constructor() {}
}
