import { QuestionData } from './question-data';

export class QuestionsDataService {
  getQuestions(): QuestionData[] {
    return [
      {
        question: 'How Can I Get Test?',
        answer:
          'You should register on our site. Then you need to make request for test period in section «Standard proxy - request test». To get confirmation you have to text to support.',
        id: 1,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Can I Buy Proxies?',
        answer:
          'You need to add credits to your balance and buy package(s) automatically in control panel in section Standard proxy - my packages.',
        id: 2,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'What Payment Methods Do You Accept?',
        answer:
          'We accept WMZ, BTC, ETH, Qiwi, Alipay, bank card and bank transfer.',
        id: 3,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Pay By QIWI?',
        answer: 'No, but you can send momeny from your QIWI wallet to WMZ.',
        id: 4,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How To Request A Refund?',
        answer:
          "A customer can request a refund via contacting RSocks customer support. Refunds for Exclusive Mix line proxies are not possible. The minimum amount of a refund is 50 USD Refunds are issued with payment system's fees deducted. Hourly/daily packages and personal proxies are not refundable. Rotating, Twitch, YouTube weekly packages are not refundable. Data center proxy packages are refundable within the first hour after activation. Mobile proxy servers are refundable within the first 24 hours and if less than 20MB of data has been spent. Other packages are refundable within the first 24 hours after activation via contacting our customer support and providing reasonable excuse for the refund.",
        id: 5,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Many Threads Can I Use?',
        answer:
          'We recommend 500 threads but you can use more than 500 (in this case we can’t guarantee hiqh quality).',
        id: 6,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Are There Any Restrictions Of Access To Packages By IPs?',
        answer:
          'Each package is available to be used only with one IP address. You can expand the authorization IP list, but this is payable service. Additional IP for work costs half from price of package.',
        id: 7,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Often Are Your Proxies Updated?',
        answer:
          'Proxies are updated automatically every 2 hours, after every update you get up to 30% of fresh proxies. IP and all ports are changed.',
        id: 8,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Is There Any Way To Disable Proxy Updates?',
        answer: 'Unfortunately, there is no way to do it.',
        id: 9,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Buy GEO-Selected Proxy?',
        answer:
          'Unfortunately this service is not available now. But you can purchase package and then use our free Proxy Checker app to filter addresses by desired country. Link for proxy checker page:',
        id: 10,
        isLink: true,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: 'https://Alpha-x-vpn.net/proxy-checker',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How To Configure Proxy Checker App?',
        answer: 'An example of Proxy Checker config is below:',
        id: 11,
        isLink: false,
        isButton: false,
        isTable: true,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: 'yahoo.com',
        port: 443,
        threads: 50,
        timeout: 10000,
        reConnect: 0,
      },
      {
        question:
          'How Fast Is IP Changed In Control Panel If I Have Dynamic IP?',
        answer:
          "For our customers we have created program that checks your IP every 10 minutes and change it. It's located in system tray and doesn't disturb you.",
        id: 12,
        isLink: false,
        isButton: true,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: 'Download «RSocks IP Changer»',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Do You Have Referral System?',
        answer: 'Yes. Our referral system conditions:',
        id: 13,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1:
          'Less than 10 referrals - 10% of their purchases; Up to 15 referrals - 15% of their purchases; More than 15 referrals - 20% of their purchases; The withdrawal of funds is from $ 50.',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Pause My Proxies?',
        answer:
          'Yes, you can purchase pauses for your subscriptions in the proxy control interface.',
        id: 14,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1: '',
        linkUrl: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
    ];
  }
  constructor() {}
}
