import { Injectable } from '@angular/core';
import { QuestionData } from '../interfaces/question-data';
import { Blog } from '../interfaces/blog';
import { ProxyList } from '../interfaces/proxy-list';
import { PopularRate } from '../interfaces/popular-rate';
import { GeneralStatistic } from '../interfaces/general-statistic';
import { ClientData } from '../../home/testimonials/interfaces/client-data';
import { IndividualRequest } from '../interfaces/individual-request';
import { PersonalPrice } from '../interfaces/personal-price';
import { PersonalQuestion } from '../interfaces/personal-question';
import { ProxyProps } from '../interfaces/proxy-props';
import { CountryProxy } from '../interfaces/country-proxy';
import { Flag } from '../interfaces/flag';
import { OfferedService } from '../interfaces/offered-service';
import { Feature } from '../../shared/interfaces/feature';
import { VpnPrice } from '../interfaces/vpn-price';
import { VpnPeriod } from '../interfaces/vpn-period';
import { ProxyChecker } from '../interfaces/proxy-checker';
import { OperatingSystem } from '../interfaces/operating-system';
import { FreeProxy } from '../interfaces/free-proxy';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  getOfferedService(): OfferedService[] {
    return [
      {
        offerdServiceId: 1,
        offerdServiceLink: '/Residential-Proxy',
        offerdServiceImgUrl:
          'assets/images/Offered-Services/residential_proxy.png',
        offerdServiceName: 'residential proxy',
        offerdServiceIsNew: false,
      },
      {
        offerdServiceId: 2,
        offerdServiceLink: '/Exclusive-Plus',
        offerdServiceImgUrl:
          'assets/images/Offered-Services/exclusive_plus.png',
        offerdServiceName: 'exclusive plus',
        offerdServiceIsNew: false,
      },
      {
        offerdServiceId: 3,
        offerdServiceLink: '/Personal-Proxy',
        offerdServiceImgUrl:
          'assets/images/Offered-Services/personal_proxy.png',
        offerdServiceName: 'personal proxy',
        offerdServiceIsNew: false,
      },
      {
        offerdServiceId: 4,
        offerdServiceLink: '/Server-Proxies',
        offerdServiceImgUrl:
          'assets/images/Offered-Services/server_proxies.png',
        offerdServiceName: 'server proxies',
        offerdServiceIsNew: false,
      },
      {
        offerdServiceId: 5,
        offerdServiceLink: '/Shared-Proxy',
        offerdServiceImgUrl: 'assets/images/Offered-Services/shared.png',
        offerdServiceName: 'shared proxy',
        offerdServiceIsNew: false,
      },
      {
        offerdServiceId: 6,
        offerdServiceLink: '/Mobile-Proxy',
        offerdServiceImgUrl: 'assets/images/Offered-Services/mobile_proxy.png',
        offerdServiceName: 'mobile proxy',
        offerdServiceIsNew: true,
      },
      {
        offerdServiceId: 7,
        offerdServiceLink: '/VPN-Service',
        offerdServiceImgUrl: 'assets/images/Offered-Services/vpn_service.png',
        offerdServiceName: 'VPN service',
        offerdServiceIsNew: false,
      },
    ];
  }
  getQuestionsData(): QuestionData[] {
    return [
      {
        question: 'How Can I Get Test?',
        answer:
          'You should register on our site. Then you need to make request for test period in section «Standard proxy - request test». To get confirmation you have to text to support.',
        id: 1,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Can I Buy Proxies?',
        answer:
          'You need to add credits to your balance and buy package(s) automatically in control panel in section Standard proxy - my packages.',
        id: 2,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'What Payment Methods Do You Accept?',
        answer:
          'We accept WMZ, BTC, ETH, Qiwi, Alipay, bank card and bank transfer.',
        id: 3,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Pay By QIWI?',
        answer: 'No, but you can send momeny from your QIWI wallet to WMZ.',
        id: 4,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How To Request A Refund?',
        answer:
          "A customer can request a refund via contacting RSocks customer support. Refunds for Exclusive Mix line proxies are not possible. The minimum amount of a refund is 50 USD Refunds are issued with payment system's fees deducted. Hourly/daily packages and personal proxies are not refundable. Rotating, Twitch, YouTube weekly packages are not refundable. Data center proxy packages are refundable within the first hour after activation. Mobile proxy servers are refundable within the first 24 hours and if less than 20MB of data has been spent. Other packages are refundable within the first 24 hours after activation via contacting our customer support and providing reasonable excuse for the refund.",
        id: 5,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Many Threads Can I Use?',
        answer:
          'We recommend 500 threads but you can use more than 500 (in this case we can’t guarantee hiqh quality).',
        id: 6,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Are There Any Restrictions Of Access To Packages By IPs?',
        answer:
          'Each package is available to be used only with one IP address. You can expand the authorization IP list, but this is payable service. Additional IP for work costs half from price of package.',
        id: 7,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How Often Are Your Proxies Updated?',
        answer:
          'Proxies are updated automatically every 2 hours, after every update you get up to 30% of fresh proxies. IP and all ports are changed.',
        id: 8,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Is There Any Way To Disable Proxy Updates?',
        answer: 'Unfortunately, there is no way to do it.',
        id: 9,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Buy GEO-Selected Proxy?',
        answer:
          'Unfortunately this service is not available now. But you can purchase package and then use our free Proxy Checker app to filter addresses by desired country. Link for proxy checker page:',
        id: 10,
        isLink: true,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: 'https://Alpha-x-vpn.net/proxy-checker',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'How To Configure Proxy Checker App?',
        answer: 'An example of Proxy Checker config is below:',
        id: 11,
        isLink: false,
        isButton: false,
        isTable: true,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: 'yahoo.com',
        port: 443,
        threads: 50,
        timeout: 10000,
        reConnect: 0,
      },
      {
        question:
          'How Fast Is IP Changed In Control Panel If I Have Dynamic IP?',
        answer:
          "For our customers we have created program that checks your IP every 10 minutes and change it. It's located in system tray and doesn't disturb you.",
        id: 12,
        isLink: false,
        isButton: true,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: 'Download «RSocks IP Changer»',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Do You Have Referral System?',
        answer: 'Yes. Our referral system conditions:',
        id: 13,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: true,
        answer1:
          'Less than 10 referrals - 10% of their purchases; Up to 15 referrals - 15% of their purchases; More than 15 referrals - 20% of their purchases; The withdrawal of funds is from $ 50.',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
      {
        question: 'Can I Pause My Proxies?',
        answer:
          'Yes, you can purchase pauses for your subscriptions in the proxy control interface.',
        id: 14,
        isLink: false,
        isButton: false,
        isTable: false,
        isAnswer1: false,
        answer1: '',
        link: '',
        buttonName: '',
        host: '',
        port: 0,
        threads: 0,
        timeout: 0,
        reConnect: 0,
      },
    ];
  }
  getBlogs(): Blog[] {
    return [
      {
        blogId: 1,
        blogName: 'New Mobile Proxy tariff: dtac (Thailand).',
        blogDescription:
          'We have added a new operator and reduced prices for all Mobile Proxy packs.',
        blogDateDay: 23,
        blogDateMonth: 'Jan',
        blogDateYear: 2019,
        blogCommentNumber: 8,
        blogViwers: 4348,
        blogShares: 27,
      },
      {
        blogId: 2,
        blogName: 'New Mobile Proxy tariff: dtac (Thailand).',
        blogDescription:
          'We have added a new operator and reduced prices for all Mobile Proxy packs.',
        blogDateDay: 23,
        blogDateMonth: 'Jan',
        blogDateYear: 2019,
        blogCommentNumber: 8,
        blogViwers: 4348,
        blogShares: 27,
      },
      {
        blogId: 3,
        blogName: 'New Mobile Proxy tariff: dtac (Thailand).',
        blogDescription:
          'We have added a new operator and reduced prices for all Mobile Proxy packs.',
        blogDateDay: 23,
        blogDateMonth: 'Jan',
        blogDateYear: 2019,
        blogCommentNumber: 8,
        blogViwers: 4348,
        blogShares: 27,
      },
    ];
  }
  getProxyList(): ProxyList[] {
    return [
      {
        proxyServiceId: 1,
        proxyServiceImgUrl: 'assets/images/pricing_table/proxy_plans.png',
        proxyServiceName: 'Proxy Plans',
        proxyServiceDesc: 'Geo, Mix and Them packages proxies.',
        proxyServiceOffers1: 'Packages from 100 to 90 000.',
        proxyServiceOffers2: 'SOCKS4/4a, SOCKS5, and HTTP/S protocols.',
        proxyServiceOffers3: 'Exclusive packages. only in one hands.',
        proxyServiceOffers4:
          'Theme package proxies for Youtube, Twitch and Email.',
        proxyServiceOffers5: 'Unlimited traffic.',
      },
      {
        proxyServiceId: 2,
        proxyServiceImgUrl:
          'assets/images/pricing_table/exclusive_plus_proxy.png',
        proxyServiceName: 'Exclusive Plus Proxy',
        proxyServiceDesc: 'Proxy lists strictly in one hand!',
        proxyServiceOffers1: 'Up to 100 000 unique IP a day.',
        proxyServiceOffers2: 'Maximum Online Stability.',
        proxyServiceOffers3: 'Support HTTP(S) ᴎ SOCKS5.',
        proxyServiceOffers4: 'Uptime 10% every hour.',
        proxyServiceOffers5: 'Crystal Clear Online (no history).',
      },
      {
        proxyServiceId: 3,
        proxyServiceImgUrl: 'assets/images/pricing_table/mobile_proxy.png',
        proxyServiceName: 'Mobile Proxy',
        proxyServiceDesc: 'Dedicated IP mobile operators.',
        proxyServiceOffers1: 'Personal IP and 10 Streams for work.',
        proxyServiceOffers2: 'No bans and high trust IP addresses.',
        proxyServiceOffers3: 'Dynamic IP change every 2 minutes.',
        proxyServiceOffers4: 'The most popular mobile operators in Europe.',
        proxyServiceOffers5: 'Support HTTP(S) and SOCKS4/4a/5.',
      },
      {
        proxyServiceId: 4,
        proxyServiceImgUrl: 'assets/images/pricing_table/personal_proxy.png',
        proxyServiceName: 'Personal Proxy',
        proxyServiceDesc: 'Dedicated IP for personal use.',
        proxyServiceOffers1: 'Individual IP.',
        proxyServiceOffers2: 'Max speed.',
        proxyServiceOffers3: 'Use for any tasks.',
        proxyServiceOffers4: 'Connecting to new locations upon request.',
        proxyServiceOffers5: 'Protocols SOCKS4, SOCKS4a, and SOCKS5.',
      },
      {
        proxyServiceId: 5,
        proxyServiceImgUrl: 'assets/images/pricing_table/server_proxies.png',
        proxyServiceName: 'Server Proxies',
        proxyServiceDesc: 'Unlimited traffic with high speed.',
        proxyServiceOffers1: '10500 IPv5 addresses.',
        proxyServiceOffers2: 'Unlimited traffic.',
        proxyServiceOffers3: 'Supports HTTP(S), Socks 4/5 protocols.',
        proxyServiceOffers4: 'High speed connection.',
        proxyServiceOffers5: 'Maximum Uptime of servers.',
      },
      {
        proxyServiceId: 6,
        proxyServiceImgUrl: 'assets/images/pricing_table/vpn_service.png',
        proxyServiceName: 'VPN Service',
        proxyServiceDesc: 'Anonymous VPN in 20 countries.',
        proxyServiceOffers1: 'No-Logs policy.',
        proxyServiceOffers2: 'Protocols: OpenVPN, PPP, HTTP, and IPsec.',
        proxyServiceOffers3: 'Single and Double VPN.',
        proxyServiceOffers4: 'Maximum speed without channel limits.',
        proxyServiceOffers5: 'Connecting to new locations upon request.',
      },
    ];
  }
  getPopularRates(): PopularRate[] {
    return [
      {
        popularRateId: 1,
        popularRateImgUrl: 'assets/images/statistics/global_mix.png',
        popularRateName: 'global mix',
        popularRateIp: '99 000 IP',
      },
      {
        popularRateId: 2,
        popularRateImgUrl: 'assets/images/statistics/mail_special.png',
        popularRateName: 'mail special',
        popularRateIp: '99 000 IP',
      },
      {
        popularRateId: 3,
        popularRateImgUrl: 'assets/images/statistics/Server_USA.png',
        popularRateName: 'server',
        popularRateIp: '5 000 IP',
      },
      {
        popularRateId: 4,
        popularRateImgUrl: 'assets/images/statistics/exclusive_plus.png',
        popularRateName: 'exclusive plus',
        popularRateIp: '10 000 IP',
      },
    ];
  }
  getGeneralStatistics(): GeneralStatistic[] {
    return [
      {
        generalStatisticId: 1,
        generalStatisticName: 'residential proxies',
        generalStatisticNumber: 150,
        generalStatisticIsK: true,
      },
      {
        generalStatisticId: 2,
        generalStatisticName: 'exclusive proxies',
        generalStatisticNumber: 290,
        generalStatisticIsK: true,
      },
      {
        generalStatisticId: 3,
        generalStatisticName: 'personal proxy countries',
        generalStatisticNumber: 40,
        generalStatisticIsK: false,
      },
      {
        generalStatisticId: 4,
        generalStatisticName: 'VPN servers countries',
        generalStatisticNumber: 21,
        generalStatisticIsK: false,
      },
    ];
  }
  getClientData(): ClientData[] {
    return [
      {
        clientId: 1,
        clientFirstName: 'Vixroo',
        clientLastName: '',
        clientImg: 'assets/images/testimonials/client-1.jpg',
        clientCommentDate: '08.01.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 2,
        clientFirstName: 'dmitri',
        clientLastName: 'ivanov',
        clientImg: 'assets/images/testimonials/client-2.jpg',
        clientCommentDate: '09.05.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 3,
        clientFirstName: 'Philip',
        clientLastName: 'Bailey',
        clientImg: 'assets/images/testimonials/client-3.jpg',
        clientCommentDate: '07.04.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 4,
        clientFirstName: 'Salma',
        clientLastName: 'Ali',
        clientImg: 'assets/images/testimonials/client-4.jpg',
        clientCommentDate: '23.05.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 5,
        clientFirstName: 'Óscar',
        clientLastName: 'García',
        clientImg: 'assets/images/testimonials/client-5.jpg',
        clientCommentDate: '06.09.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 6,
        clientFirstName: 'Scarlet',
        clientLastName: 'Olsen',
        clientImg: 'assets/images/testimonials/client-6.jpg',
        clientCommentDate: '15.12.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 7,
        clientFirstName: 'King',
        clientLastName: 'YU',
        clientImg: 'assets/images/testimonials/client-7.jpg',
        clientCommentDate: '14.07.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 8,
        clientFirstName: 'Amber',
        clientLastName: 'Conley',
        clientImg: 'assets/images/testimonials/client-8.jpg',
        clientCommentDate: '09.09.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 9,
        clientFirstName: 'Ali',
        clientLastName: 'Ibrahim',
        clientImg: 'assets/images/testimonials/client-9.jpg',
        clientCommentDate: '08.07.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 10,
        clientFirstName: 'Alisa',
        clientLastName: 'Chung',
        clientImg: 'assets/images/testimonials/client-10.jpg',
        clientCommentDate: '24.05.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 11,
        clientFirstName: 'Gustavo',
        clientLastName: 'Flores',
        clientImg: 'assets/images/testimonials/client-11.jpg',
        clientCommentDate: '29.08.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 12,
        clientFirstName: 'Eva',
        clientLastName: 'Osborne',
        clientImg: 'assets/images/testimonials/client-12.jpg',
        clientCommentDate: '28.11.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 13,
        clientFirstName: 'Zechariah',
        clientLastName: 'Wyatt',
        clientImg: 'assets/images/testimonials/client-13.jpg',
        clientCommentDate: '03.04.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
      {
        clientId: 14,
        clientFirstName: 'Isabelle',
        clientLastName: 'Hughes',
        clientImg: 'assets/images/testimonials/client-14.jpg',
        clientCommentDate: '13.02.2022',
        clientCommentOpinion:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit.Placeat aut consequatur illo animi optio exercitationem doloribus eligendi iusto.',
      },
    ];
  }
  getIndividualRequests(): IndividualRequest[] {
    return [
      {
        id: 1,
        name: 'Proxies of any country',
        icon: 'query_benefit_1',
      },
      {
        id: 2,
        name: 'Fast launch of new proxies on request',
        icon: 'query_benefit_2',
      },
      {
        id: 3,
        name: 'Order volume starts from 100 IPs',
        icon: 'query_benefit_3',
      },
    ];
  }
  getPersonalPrices(): PersonalPrice[] {
    return [
      {
        id: 1,
        name: 'Private',
        serviceName: 'Personal Proxy',
        price: 5.0,
        period: 'from 30 days',
        features: [
          'Data Center Proxy',
          'IP assigned only to you!',
          '51 countries to choose from!',
          'Choose proxy fingerprint',
          'Unlimited data',
          'Unlimited bandwidth',
          'HTTPS/SOCKS5 supporеtd',
          'Authorization by IP or login:password',
          '25, 465, and 587 ports are closed',
          'Spamming, cracking, carding, and scanning are not allowed',
        ],
        featuresIcon: [
          'assets/images/personal_proxy/pricing_table/server.png',
          'assets/images/personal_proxy/pricing_table/user.png',
          'assets/images/personal_proxy/pricing_table/globe.png',
          'assets/images/personal_proxy/pricing_table/fingerprint.png',
          'assets/images/personal_proxy/pricing_table/forever.png',
          'assets/images/personal_proxy/pricing_table/rocket.png',
          'assets/images/personal_proxy/pricing_table/shield.png',
          'assets/images/personal_proxy/pricing_table/lock.png',
          'assets/images/personal_proxy/pricing_table/block.png',
          'assets/images/personal_proxy/pricing_table/block.png',
        ],
      },
      {
        id: 2,
        name: 'Shared',
        serviceName: 'Personal Proxy',
        price: 0.2,
        period: 'from 30 days',
        features: [
          'Data Center Proxy',
          'Several users per IP',
          '14 countries are available',
          'Choose activity groups',
          'Unlimited data',
          'Unlimited bandwidth',
          'HTTPS/SOCKS5 supporеtd',
          'Authorization by IP or login:password',
          '25, 465, and 587 ports are closed',
          'Spamming, cracking, carding, and scanning are not allowed',
        ],
        featuresIcon: [
          'assets/images/personal_proxy/pricing_table/server.png',
          'assets/images/personal_proxy/pricing_table/group.png',
          'assets/images/personal_proxy/pricing_table/globe.png',
          'assets/images/personal_proxy/pricing_table/switch.png',
          'assets/images/personal_proxy/pricing_table/forever.png',
          'assets/images/personal_proxy/pricing_table/rocket.png',
          'assets/images/personal_proxy/pricing_table/shield.png',
          'assets/images/personal_proxy/pricing_table/lock.png',
          'assets/images/personal_proxy/pricing_table/block.png',
          'assets/images/personal_proxy/pricing_table/block.png',
        ],
      },
    ];
  }
  getPersonalQuestions(): PersonalQuestion[] {
    return [
      {
        id: 1,
        question: 'Can I Choose A Certain City?',
        answers:
          'Basically not, though you can contact our support and they will try to find the city you need.',
      },
      {
        id: 2,
        question: 'What Authorization Methods Are Supported?',
        answers:
          'You can choose to authorize either by login and password or you you can authorize by a whitelisted IP address.',
      },
      {
        id: 3,
        question:
          'How Many Times Can You Change My Credentials Or Whitelisted IP Address?',
        answers: 'There is no limit at this point.',
      },
      {
        id: 4,
        question: 'How Much Bandwidth Is Given To A Proxy?',
        answers: 'All personal proxies have 100 MB/s bandwidth.',
      },
      {
        id: 5,
        question: 'Are They Suitable For My Service?',
        answers: 'We recommend you to contact our support to get more details.',
      },
      {
        id: 6,
        question: 'Do You Have X Country?',
        answers:
          'If you were unlucky to find a certain country, be sure to make a request for adding this country and contact our support.',
      },
      {
        id: 8,
        question: 'Are Personal Proxies Refundable?',
        answers: 'Personal proxies are not refundable.',
      },
      {
        id: 9,
        question: 'What Protocols Do Proxies Support?',
        answers:
          'Our proxies support all major protocols such as HTTP(s), SOCKS4/4a/5.',
      },
    ];
  }
  getProxiesProps(): ProxyProps[] {
    return [
      {
        id: 1,
        name: 'SECURITY',
        icon: 'benefit-1',
        describtion:
          'Authorization and secure connection make our proxies the most reliable solution.',
      },
      {
        id: 2,
        name: 'STABILITY',
        icon: 'benefit-2',
        describtion:
          'High bandwidth and static IP address are guaranteed for the whole period of use.',
      },
      {
        id: 3,
        name: 'PRIVACY',
        icon: 'benefit-3',
        describtion:
          'Proxies are assigned to one or there users depending on plan type (Private or Shareable).',
      },
      {
        id: 4,
        name: 'GEO-LOCATION',
        icon: 'benefit-4',
        describtion: 'Choose from more 40 countries or place a custom-order.',
      },
      {
        id: 5,
        name: 'MULTITASKING',
        icon: 'benefit-5',
        describtion:
          'Circumvent region blocks, work on social media networks, parse data or play online games.',
      },
      {
        id: 6,
        name: 'VERSATILITY',
        icon: 'benefit-6',
        describtion: 'Support of SOCKS4/4a, SOCKS5, HTTP/S and high speed.',
      },
    ];
  }
  getCountriesProxy(): CountryProxy[] {
    return [
      {
        id: '1',
        name: 'United States',
        alpha2Code: 'us',
        alpha3Code: 'usa',
        numericCode: '840',
        callingCode: '1',
        icon: 'us',
        cities: ['New York', 'Los Angeles', 'Nevada', 'Illinois'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 20496,
        ipAvailiblePrivate: 277,
        ipAvailiblePrivateCities: [27, 47, 97, 47],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '2',
        name: 'United Kingdom',
        alpha2Code: 'uk',
        alpha3Code: 'gbr',
        numericCode: '826',
        callingCode: '44',
        icon: 'uk',
        cities: ['London', 'Manchester', 'Liverpool', 'Birmingham'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 70,
        ipAvailiblePrivateCities: [10, 23, 30, 14],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '3',
        name: 'Germany',
        alpha2Code: 'de',
        alpha3Code: 'deu',
        numericCode: '276',
        callingCode: '49',
        icon: 'de',
        cities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2022,
        ipAvailiblePrivate: 86,
        ipAvailiblePrivateCities: [20, 30, 20, 16],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '4',
        name: 'France',
        alpha2Code: 'fr',
        alpha3Code: 'fra',
        numericCode: '250',
        callingCode: '33',
        icon: 'fr',
        cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 46,
        ipAvailiblePrivateCities: [19, 25, 41, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 30, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '5',
        name: 'Canada',
        alpha2Code: 'ca',
        alpha3Code: 'can',
        numericCode: '124',
        callingCode: '1',
        icon: 'ca',
        cities: ['Toronto', 'Montreal', 'Vancouver', 'Ottawa'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [16, 25, 28, 15],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '6',
        name: 'Albania',
        alpha2Code: 'al',
        alpha3Code: 'alb',
        numericCode: '8',
        callingCode: '355',
        icon: 'al',
        cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [26, 15, 21, 23],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '7',
        name: 'Australia',
        alpha2Code: 'au',
        alpha3Code: 'aus',
        numericCode: '36',
        callingCode: '61',
        icon: 'au',
        cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 15, 5, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '8',
        name: 'Austria',
        alpha2Code: 'at',
        alpha3Code: 'aut',
        numericCode: '40',
        callingCode: '43',
        icon: 'at',
        cities: ['Vienna', 'Graz', 'Linz', 'Salzburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [14, 11, 9, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '9',
        name: 'Belarus',
        alpha2Code: 'by',
        alpha3Code: 'blr',
        numericCode: '112',
        callingCode: '375',
        icon: 'by',
        cities: ['Minsk', 'Gomel', 'Mogilev', 'Brest'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '10',
        name: 'Bosna and Herzegovina',
        alpha2Code: 'ba',
        alpha3Code: 'bih',
        numericCode: '70',
        callingCode: '387',
        icon: 'ba',
        cities: ['Sarajevo', 'Banja Luka', 'Zenica', 'Tuzla'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [2, 7, 4, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '11',
        name: 'Brazil',
        alpha2Code: 'br',
        alpha3Code: 'bra',
        numericCode: '76',
        callingCode: '55',
        icon: 'br',
        cities: ['Sao Paulo', 'Rio de Janeiro', 'Salvador', 'Brasilia'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 39,
        ipAvailiblePrivateCities: [13, 19, 8, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 50, 100],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '12',
        name: 'Bulgaria',
        alpha2Code: 'bg',
        alpha3Code: 'bgr',
        numericCode: '100',
        callingCode: '359',
        icon: 'bg',
        cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 13,
        ipAvailiblePrivateCities: [4, 5, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '13',
        name: 'Cyprus',
        alpha2Code: 'cy',
        alpha3Code: 'cyp',
        numericCode: '196',
        callingCode: '357',
        icon: 'cy',
        cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '14',
        name: 'Czech Republic',
        alpha2Code: 'cz',
        alpha3Code: 'cze',
        numericCode: '203',
        callingCode: '420',
        icon: 'cz',
        cities: ['Prague', 'Brno', 'Ostrava', 'Plzen'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '15',
        name: 'Egypt',
        alpha2Code: 'eg',
        alpha3Code: 'egy',
        numericCode: '818',
        callingCode: '20',
        icon: 'eg',
        cities: ['Cairo', 'Alexandria', 'Giza', 'Ash-Sharqia'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '16',
        name: 'Estonia',
        alpha2Code: 'ee',
        alpha3Code: 'est',
        numericCode: '233',
        callingCode: '372',
        icon: 'ee',
        cities: ['Tallinn', 'Tartu', 'Narva', 'Parnu'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 34,
        ipAvailiblePrivateCities: [10, 7, 13, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '17',
        name: 'Finland',
        alpha2Code: 'fi',
        alpha3Code: 'fin',
        numericCode: '246',
        callingCode: '358',
        icon: 'fi',
        cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 6, 8, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '18',
        name: 'Greece',
        alpha2Code: 'gr',
        alpha3Code: 'grc',
        numericCode: '300',
        callingCode: '30',
        icon: 'gr',
        cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 978,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '19',
        name: 'Hong Kong',
        alpha2Code: 'hk',
        alpha3Code: 'hkg',
        numericCode: '344',
        callingCode: '852',
        icon: 'hk',
        cities: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '20',
        name: 'Hungary',
        alpha2Code: 'hu',
        alpha3Code: 'hun',
        numericCode: '348',
        callingCode: '36',
        icon: 'hu',
        cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 11,
        ipAvailiblePrivateCities: [4, 3, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '21',
        name: 'India',
        alpha2Code: 'in',
        alpha3Code: 'ind',
        numericCode: '356',
        callingCode: '91',
        icon: 'in',
        cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '22',
        name: 'Ireland',
        alpha2Code: 'ie',
        alpha3Code: 'irl',
        numericCode: '372',
        callingCode: '353',
        icon: 'ie',
        cities: ['Dublin', 'Cork', 'Limerick', 'Galway'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '23',
        name: 'Palestine',
        alpha2Code: 'ps',
        alpha3Code: 'pse',
        numericCode: '275',
        callingCode: '970',
        icon: 'ps',
        cities: ['Gaza', 'Jerusalem', 'Nablus', 'Rafah'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [3, 15, 30],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '24',
        name: 'Italy',
        alpha2Code: 'it',
        alpha3Code: 'ita',
        numericCode: '380',
        callingCode: '39',
        icon: 'it',
        cities: ['Rome', 'Milan', 'Naples', 'Turin'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1003,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '25',
        name: 'Japan',
        alpha2Code: 'jp',
        alpha3Code: 'jpn',
        numericCode: '392',
        callingCode: '81',
        icon: 'jp',
        cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2013,
        ipAvailiblePrivate: 48,
        ipAvailiblePrivateCities: [15, 20, 8, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '26',
        name: 'Kazakhstan',
        alpha2Code: 'kz',
        alpha3Code: 'kaz',
        numericCode: '398',
        callingCode: '7',
        icon: 'kz',
        cities: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 10, 5, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '27',
        name: 'Kenya',
        alpha2Code: 'ke',
        alpha3Code: 'ken',
        numericCode: '404',
        callingCode: '254',
        icon: 'ke',
        cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 20,
        ipAvailiblePrivateCities: [6, 8, 4, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '28',
        name: 'Latvia',
        alpha2Code: 'lv',
        alpha3Code: 'lva',
        numericCode: '428',
        callingCode: '371',
        icon: 'lv',
        cities: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [8, 7, 6, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '29',
        name: 'Luxembourg',
        alpha2Code: 'lu',
        alpha3Code: 'lux',
        numericCode: '442',
        callingCode: '352',
        icon: 'lu',
        cities: ['Luxembourg', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 36,
        ipAvailiblePrivateCities: [10, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '30',
        name: 'Malaysia',
        alpha2Code: 'my',
        alpha3Code: 'mys',
        numericCode: '458',
        callingCode: '60',
        icon: 'my',
        cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '31',
        name: 'Mexico',
        alpha2Code: 'mx',
        alpha3Code: 'mex',
        numericCode: '484',
        callingCode: '52',
        icon: 'mx',
        cities: ['Mexico City', 'Ecatepec', 'Guadalajara', 'Puebla'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 15,
        ipAvailiblePrivateCities: [5, 4, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '32',
        name: 'Netherlands',
        alpha2Code: 'nl',
        alpha3Code: 'nld',
        numericCode: '528',
        callingCode: '31',
        icon: 'nl',
        cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1018,
        ipAvailiblePrivate: 42,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '33',
        name: 'New Zealand',
        alpha2Code: 'nz',
        alpha3Code: 'nzl',
        numericCode: '554',
        callingCode: '64',
        icon: 'nz',
        cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '34',
        name: 'Norway',
        alpha2Code: 'no',
        alpha3Code: 'nor',
        numericCode: '578',
        callingCode: '47',
        icon: 'no',
        cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 62,
        ipAvailiblePrivateCities: [20, 20, 12, 10],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '35',
        name: 'Poland',
        alpha2Code: 'pl',
        alpha3Code: 'pol',
        numericCode: '616',
        callingCode: '48',
        icon: 'pl',
        cities: ['Warsaw', 'Krakow', 'Lodz', 'Wroclaw'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [6, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '36',
        name: 'Portugal',
        alpha2Code: 'pt',
        alpha3Code: 'prt',
        numericCode: '620',
        callingCode: '351',
        icon: 'pt',
        cities: ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: ' disabled',
        ipAvailibleShared: 756,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '37',
        name: 'Republic of Korea',
        alpha2Code: 'kr',
        alpha3Code: 'kor',
        numericCode: '410',
        callingCode: '82',
        icon: 'kr',
        cities: ['Seoul', 'Busan', 'Incheon', 'Daegu'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '38',
        name: 'Republic of Lithuania',
        alpha2Code: 'lt',
        alpha3Code: 'ltu',
        numericCode: '440',
        callingCode: '370',
        icon: 'lt',
        cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '39',
        name: 'Republic of Moldova',
        alpha2Code: 'md',
        alpha3Code: 'mda',
        numericCode: '498',
        callingCode: '373',
        icon: 'md',
        cities: ['Chisinau', 'Tiraspol', 'Balti', 'Bender'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 55,
        ipAvailiblePrivateCities: [17, 20, 10, 8],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '40',
        name: 'Romania',
        alpha2Code: 'ro',
        alpha3Code: 'rou',
        numericCode: '642',
        callingCode: '40',
        icon: 'ro',
        cities: ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 27,
        ipAvailiblePrivateCities: [8, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '41',
        name: 'Russia',
        alpha2Code: 'ru',
        alpha3Code: 'rus',
        numericCode: '643',
        callingCode: '7',
        icon: 'ru',
        cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2120,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '42',
        name: 'Singapore',
        alpha2Code: 'sg',
        alpha3Code: 'sgp',
        numericCode: '702',
        callingCode: '65',
        icon: 'sg',
        cities: ['Singapore', 'Woodlands', 'Jurong East', 'Tampines'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 81,
        ipAvailiblePrivateCities: [25, 30, 15, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '44',
        name: 'Slovakia',
        alpha2Code: 'sk',
        alpha3Code: 'svk',
        numericCode: '703',
        callingCode: '421',
        icon: 'sk',
        cities: ['Bratislava', 'Kosice', 'Presov', 'Nitra'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 18,
        ipAvailiblePrivateCities: [5, 6, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '45',
        name: 'South Africa',
        alpha2Code: 'za',
        alpha3Code: 'zaf',
        numericCode: '710',
        callingCode: '27',
        icon: 'za',
        cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 856,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '46',
        name: 'Spain',
        alpha2Code: 'es',
        alpha3Code: 'esp',
        numericCode: '724',
        callingCode: '34',
        icon: 'es',
        cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '47',
        name: 'Sweden',
        alpha2Code: 'se',
        alpha3Code: 'swe',
        numericCode: '752',
        callingCode: '46',
        icon: 'se',
        cities: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '48',
        name: 'Switzerland',
        alpha2Code: 'ch',
        alpha3Code: 'che',
        numericCode: '756',
        callingCode: '41',
        icon: 'ch',
        cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '49',
        name: 'Thailand',
        alpha2Code: 'th',
        alpha3Code: 'tha',
        numericCode: '764',
        callingCode: '66',
        icon: 'th',
        cities: ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 28,
        ipAvailiblePrivateCities: [9, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [9, 45, 90],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '50',
        name: 'Turkey',
        alpha2Code: 'tr',
        alpha3Code: 'tur',
        numericCode: '792',
        callingCode: '90',
        icon: 'tr',
        cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1031,
        ipAvailiblePrivate: 24,
        ipAvailiblePrivateCities: [7, 9, 5, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '51',
        name: 'Ukraine',
        alpha2Code: 'ua',
        alpha3Code: 'ukr',
        numericCode: '804',
        callingCode: '380',
        icon: 'ua',
        cities: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1021,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '52',
        name: 'United Arab Emirates',
        alpha2Code: 'ae',
        alpha3Code: 'are',
        numericCode: '784',
        callingCode: '971',
        icon: 'ae',
        cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1045,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '53',
        name: 'Vietnam',
        alpha2Code: 'vn',
        alpha3Code: 'vnm',
        numericCode: '704',
        callingCode: '84',
        icon: 'vn',
        cities: ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Da Nang'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 18,
        ipAvailiblePrivateCities: [5, 6, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '54',
        name: 'Uzbekistan',
        alpha2Code: 'uz',
        alpha3Code: 'uzb',
        numericCode: '860',
        callingCode: '998',
        icon: 'uz',
        cities: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '55',
        name: 'Saudi Arabia',
        alpha2Code: 'sa',
        alpha3Code: 'sau',
        numericCode: '682',
        callingCode: '966',
        icon: 'sa',
        cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1004,
        ipAvailiblePrivate: 20,
        ipAvailiblePrivateCities: [6, 8, 4, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '56',
        name: 'Serbia',
        alpha2Code: 'rs',
        alpha3Code: 'srb',
        numericCode: '688',
        callingCode: '381',
        icon: 'rs',
        cities: ['Belgrade', 'Novi Sad', 'Nis', 'Zemun'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 21,
        ipAvailiblePrivateCities: [6, 8, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '57',
        name: 'Sri Lanka',
        alpha2Code: 'lk',
        alpha3Code: 'lka',
        numericCode: '144',
        callingCode: '94',
        icon: 'lk',
        cities: ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Negombo'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 14,
        ipAvailiblePrivateCities: [4, 5, 2, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '58',
        name: 'Tunisia',
        alpha2Code: 'tn',
        alpha3Code: 'tun',
        numericCode: '788',
        callingCode: '216',
        icon: 'tn',
        cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '59',
        name: 'Qatar',
        alpha2Code: 'qa',
        alpha3Code: 'qat',
        numericCode: '634',
        callingCode: '974',
        icon: 'qa',
        cities: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 987,
        ipAvailiblePrivate: 24,
        ipAvailiblePrivateCities: [7, 9, 4, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '60',
        name: 'Philippines',
        alpha2Code: 'ph',
        alpha3Code: 'phl',
        numericCode: '608',
        callingCode: '63',
        icon: 'ph',
        cities: ['Quezon City', 'Manila', 'Davao City', 'Caloocan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 15,
        ipAvailiblePrivateCities: [5, 4, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '61',
        name: 'Pakistan',
        alpha2Code: 'pk',
        alpha3Code: 'pak',
        numericCode: '586',
        callingCode: '92',
        icon: 'pk',
        cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
    ];
  }
  getFlags(): Flag[] {
    return [
      {
        id: 1,
        name: 'uk',
        title: 'United Kingdom',
        alt: 'United Kingdom',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 2,
        name: 'jp',
        title: 'Japan',
        alt: 'Japan',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 3,
        name: 'br',
        title: 'Brazil',
        alt: 'Brazil',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 4,
        name: 'au-hk',
        title: 'Australia-Hong Kong',
        alt: 'Australia-Hong Kong',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 5,
        name: 'us',
        title: 'United States',
        alt: 'United States',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 6,
        name: '',
        title: '',
        alt: '',
        classBoth: '',
        classHuge: ' --huge',
        isBack: false,
        isInfo: true,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 7,
        name: 'nl',
        title: 'Netherlands',
        alt: 'Netherlands',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 8,
        name: 'fr-es',
        title: 'France-Spain',
        alt: 'France-Spain',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-3',
      },
      {
        id: 9,
        name: 'mx',
        title: 'Mexico',
        alt: 'Mexico',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 10,
        name: 'in',
        title: 'India',
        alt: 'India',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 11,
        name: 'de-be',
        title: 'Germany-Belgium',
        alt: 'Germany-Belgium',
        classBoth: ' both-span',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-5',
      },
      {
        id: 12,
        name: 'it',
        title: 'Italy',
        alt: 'Italy',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 13,
        name: 'ca-id',
        title: 'Canada-Indonesia',
        alt: 'Canada-Indonesia',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-10',
      },
      {
        id: 14,
        name: 'ru',
        title: 'Russia',
        alt: 'Russia',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 15,
        name: 'ua',
        title: 'Ukraine',
        alt: 'Ukraine',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 16,
        name: 'in',
        title: 'India',
        alt: 'India',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 17,
        name: 'cn',
        title: 'China',
        alt: 'China',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 18,
        name: 'kr',
        title: 'South Korea',
        alt: 'South Korea',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 19,
        name: 'co',
        title: 'Colombia',
        alt: 'Colombia',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 20,
        name: 'pl',
        title: 'Poland',
        alt: 'Poland',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 21,
        name: 'se',
        title: 'Sweden',
        alt: 'Sweden',
        classBoth: ' both-span',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 22,
        name: 'ph',
        title: 'Philippines',
        alt: 'Philippines',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 23,
        name: 'pt',
        title: 'Portugal',
        alt: 'Portugal',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 24,
        name: 'sg',
        title: 'Singapore',
        alt: 'Singapore',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 25,
        name: 'vd-th',
        title: 'Vietnam-Thailand',
        alt: 'Vietnam-Thailand',
        classBoth: '',
        classHuge: '',
        isBack: true,
        isInfo: false,
        isDelayed: true,
        delatedClass: ' delayed-15',
      },
      {
        id: 26,
        name: 'ar',
        title: 'Argentina',
        alt: 'Argentina',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 27,
        name: 'ch',
        title: 'Switzerland',
        alt: 'Switzerland',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 28,
        name: 'tr',
        title: 'Turkey',
        alt: 'Turkey',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
      {
        id: 29,
        name: 'tw',
        title: 'Taiwan',
        alt: 'Taiwan',
        classBoth: '',
        classHuge: '',
        isBack: false,
        isInfo: false,
        isDelayed: false,
        delatedClass: '',
      },
    ];
  }
  getFeatures(): Feature[] {
    return [
      {
        id: 1,
        name: 'Fast start',
        description:
          'Launching your own proxy rental service will not require a serious investment of time, money and technical resources.',
        icon: 'assets/images/white_label/you_get/fast.svg',
      },
      {
        id: 2,
        name: 'Branding',
        description:
          'The service will work on your domain, the site and cabinet will be designed in your corporate style.',
        icon: 'assets/images/white_label/you_get/brand.svg',
      },
      {
        id: 3,
        name: 'Infrastructure',
        description:
          'You immediately get a platform that implements all the possibilities for clients to work with proxy services.',
        icon: 'assets/images/white_label/you_get/infrastructure.svg',
      },
      {
        id: 4,
        name: 'Updates',
        description:
          'We provide constant and free updates of the system core and all elements of the platform.',
        icon: 'assets/images/white_label/you_get/update.svg',
      },
      {
        id: 5,
        name: 'Multilingual',
        description:
          'You can connect ready-made translations of the project into English, Chinese and Spanish to enter new markets.',
        icon: 'assets/images/white_label/you_get/language.svg',
      },
      {
        id: 6,
        name: 'API',
        description:
          'Your clients will have support for all the features of the platform API. We will add new ones upon request.',
        icon: 'assets/images/white_label/you_get/api.svg',
      },
      {
        id: 7,
        name: 'Terms',
        description:
          'Unlike the affiliate program, for White Label partners we give unique conditions for the cost of packages.',
        icon: 'assets/images/white_label/you_get/condition.svg',
      },
      {
        id: 8,
        name: 'Back support',
        description:
          'Professional technical support for your business will ensure prompt resolution of any complex issues.',
        icon: 'assets/images/white_label/you_get/support.svg',
      },
    ];
  }
  getFreeProxies(): FreeProxy[] {
    return [
      {
        id: 1,
        name: 'unlimited traffic',
        description:
          'Unlimited traffic on any proxy packs for complete freedom in the Internet',
        icon: 'assets/images/shared_proxy/pack_individ/unlimited_traffic.svg',
      },
      {
        id: 2,
        name: 'wide choice of locations',
        description:
          'Unlimited traffic on any proxy packs for complete freedom in the Internet',
        icon: 'assets/images/shared_proxy/pack_individ/wide_choice_of_locations.svg',
      },
      {
        id: 3,
        name: 'support all protocols',
        description:
          'Unlimited traffic on any proxy packs for complete freedom in the Internet',
        icon: 'assets/images/shared_proxy/pack_individ/support_all_protocols.svg',
      },
      {
        id: 4,
        name: 'all-in-one solution',
        description:
          'Unlimited traffic on any proxy packs for complete freedom in the Internet',
        icon: 'assets/images/shared_proxy/pack_individ/all_in_one_solution.svg',
      },
    ];
  }
  getOperatingSystems(): OperatingSystem[] {
    return [
      {
        id: 1,
        name: 'Windows',
        icon: 'faWindows',
        version: '7, 8, 10',
        worksOn: 'V.3.0.9',
      },
      {
        id: 2,
        name: 'Linux',
        icon: 'faLinux',
        version: 'Ubuntu, Debian, Fedora, CentOS, Arch Linux',
        worksOn: 'V.3.0.9',
      },
      {
        id: 3,
        name: 'Mac OS',
        icon: 'faApple',
        version: 'OS X',
        worksOn: 'V.3.0.9',
      },
    ];
  }
  getProxiesCheckers(): ProxyChecker[] {
    return [
      {
        id: 1,
        name: 'Country and city geo-location filter',
        icon: 'assets/images/shared_proxy/shared_checker/location.svg',
        position: 'left',
      },
      {
        id: 2,
        name: 'Speed and latency checking',
        icon: 'assets/images/shared_proxy/shared_checker/time.svg',
        position: 'left',
      },
      {
        id: 3,
        name: 'Proxy IP address detection',
        icon: 'assets/images/shared_proxy/shared_checker/ip.svg',
        position: 'left',
      },
      {
        id: 4,
        name: 'PTR-record and the anonymity level',
        icon: 'assets/images/shared_proxy/shared_checker/hacker.svg',
        position: 'right',
      },
      {
        id: 5,
        name: 'Spamhaus records checking',
        icon: 'assets/images/shared_proxy/shared_checker/share.svg',
        position: 'right',
      },
      {
        id: 6,
        name: 'Export results in your own format',
        icon: 'assets/images/shared_proxy/shared_checker/export-document.svg',
        position: 'right',
      },
    ];
  }
  getVpnPeriods(): VpnPeriod[] {
    return [
      {
        id: 1,
        name: 'Test Period',
        description: 'Speed is 10 mb/s',
        button: 'Try for free',
        counteis: ['Netherlands', 'United States', 'Russia'],
      },
    ];
  }
  getVpnPrices(): VpnPrice[] {
    return [
      {
        id: 1,
        name: 'SINGLE',
        description: 'High anonymity level at a reasonable price',
        icon: 'assets/images/vpn/Price_VPN/single-title2.svg',
        priceMonth: 9.9,
        priceHalfYear: 49.9,
        priceYear: 99.9,
      },
    ];
  }
  getSharedPrices() {
    return [
      {
        title: 'Shared',
        featuresName: ['Online', 'Updates', 'Threads', 'Day / Month'],
        features: [
          '10 000 - 20 000 IP',
          'Up to 20% every 3 hours',
          '300',
          '$3 / $10',
        ],
      },
    ];
  }
  constructor() {}
}
