import { Injectable } from '@angular/core';
import { CountryProxy } from '../interfaces/country-proxy';

@Injectable({
  providedIn: 'root',
})
export class CountriesProxyService {
  getCountriesProxy(): CountryProxy[] {
    return [
      {
        id: '1',
        name: 'United States',
        alpha2Code: 'us',
        alpha3Code: 'usa',
        numericCode: '840',
        callingCode: '1',
        icon: 'us',
        cities: ['New York', 'Los Angeles', 'Nevada', 'Illinois'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 20496,
        ipAvailiblePrivate: 277,
        ipAvailiblePrivateCities: [27, 47, 97, 47],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '2',
        name: 'United Kingdom',
        alpha2Code: 'uk',
        alpha3Code: 'gbr',
        numericCode: '826',
        callingCode: '44',
        icon: 'uk',
        cities: ['London', 'Manchester', 'Liverpool', 'Birmingham'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 70,
        ipAvailiblePrivateCities: [10, 23, 30, 14],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '3',
        name: 'Germany',
        alpha2Code: 'de',
        alpha3Code: 'deu',
        numericCode: '276',
        callingCode: '49',
        icon: 'de',
        cities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2022,
        ipAvailiblePrivate: 86,
        ipAvailiblePrivateCities: [20, 30, 20, 16],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '4',
        name: 'France',
        alpha2Code: 'fr',
        alpha3Code: 'fra',
        numericCode: '250',
        callingCode: '33',
        icon: 'fr',
        cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 46,
        ipAvailiblePrivateCities: [19, 25, 41, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 30, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '5',
        name: 'Canada',
        alpha2Code: 'ca',
        alpha3Code: 'can',
        numericCode: '124',
        callingCode: '1',
        icon: 'ca',
        cities: ['Toronto', 'Montreal', 'Vancouver', 'Ottawa'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [16, 25, 28, 15],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '6',
        name: 'Albania',
        alpha2Code: 'al',
        alpha3Code: 'alb',
        numericCode: '8',
        callingCode: '355',
        icon: 'al',
        cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [26, 15, 21, 23],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '7',
        name: 'Australia',
        alpha2Code: 'au',
        alpha3Code: 'aus',
        numericCode: '36',
        callingCode: '61',
        icon: 'au',
        cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 15, 5, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '8',
        name: 'Austria',
        alpha2Code: 'at',
        alpha3Code: 'aut',
        numericCode: '40',
        callingCode: '43',
        icon: 'at',
        cities: ['Vienna', 'Graz', 'Linz', 'Salzburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [14, 11, 9, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '9',
        name: 'Belarus',
        alpha2Code: 'by',
        alpha3Code: 'blr',
        numericCode: '112',
        callingCode: '375',
        icon: 'by',
        cities: ['Minsk', 'Gomel', 'Mogilev', 'Brest'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '10',
        name: 'Bosna and Herzegovina',
        alpha2Code: 'ba',
        alpha3Code: 'bih',
        numericCode: '70',
        callingCode: '387',
        icon: 'ba',
        cities: ['Sarajevo', 'Banja Luka', 'Zenica', 'Tuzla'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [2, 7, 4, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '11',
        name: 'Brazil',
        alpha2Code: 'br',
        alpha3Code: 'bra',
        numericCode: '76',
        callingCode: '55',
        icon: 'br',
        cities: ['Sao Paulo', 'Rio de Janeiro', 'Salvador', 'Brasilia'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 39,
        ipAvailiblePrivateCities: [13, 19, 8, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 50, 100],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '12',
        name: 'Bulgaria',
        alpha2Code: 'bg',
        alpha3Code: 'bgr',
        numericCode: '100',
        callingCode: '359',
        icon: 'bg',
        cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 13,
        ipAvailiblePrivateCities: [4, 5, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '13',
        name: 'Cyprus',
        alpha2Code: 'cy',
        alpha3Code: 'cyp',
        numericCode: '196',
        callingCode: '357',
        icon: 'cy',
        cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '14',
        name: 'Czech Republic',
        alpha2Code: 'cz',
        alpha3Code: 'cze',
        numericCode: '203',
        callingCode: '420',
        icon: 'cz',
        cities: ['Prague', 'Brno', 'Ostrava', 'Plzen'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '15',
        name: 'Egypt',
        alpha2Code: 'eg',
        alpha3Code: 'egy',
        numericCode: '818',
        callingCode: '20',
        icon: 'eg',
        cities: ['Cairo', 'Alexandria', 'Giza', 'Ash-Sharqia'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '16',
        name: 'Estonia',
        alpha2Code: 'ee',
        alpha3Code: 'est',
        numericCode: '233',
        callingCode: '372',
        icon: 'ee',
        cities: ['Tallinn', 'Tartu', 'Narva', 'Parnu'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 34,
        ipAvailiblePrivateCities: [10, 7, 13, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '17',
        name: 'Finland',
        alpha2Code: 'fi',
        alpha3Code: 'fin',
        numericCode: '246',
        callingCode: '358',
        icon: 'fi',
        cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 6, 8, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '18',
        name: 'Greece',
        alpha2Code: 'gr',
        alpha3Code: 'grc',
        numericCode: '300',
        callingCode: '30',
        icon: 'gr',
        cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 978,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '19',
        name: 'Hong Kong',
        alpha2Code: 'hk',
        alpha3Code: 'hkg',
        numericCode: '344',
        callingCode: '852',
        icon: 'hk',
        cities: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '20',
        name: 'Hungary',
        alpha2Code: 'hu',
        alpha3Code: 'hun',
        numericCode: '348',
        callingCode: '36',
        icon: 'hu',
        cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 11,
        ipAvailiblePrivateCities: [4, 3, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '21',
        name: 'India',
        alpha2Code: 'in',
        alpha3Code: 'ind',
        numericCode: '356',
        callingCode: '91',
        icon: 'in',
        cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '22',
        name: 'Ireland',
        alpha2Code: 'ie',
        alpha3Code: 'irl',
        numericCode: '372',
        callingCode: '353',
        icon: 'ie',
        cities: ['Dublin', 'Cork', 'Limerick', 'Galway'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '23',
        name: 'Palestine',
        alpha2Code: 'ps',
        alpha3Code: 'pse',
        numericCode: '275',
        callingCode: '970',
        icon: 'ps',
        cities: ['Gaza', 'Jerusalem', 'Nablus', 'Rafah'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [3, 15, 30],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '24',
        name: 'Italy',
        alpha2Code: 'it',
        alpha3Code: 'ita',
        numericCode: '380',
        callingCode: '39',
        icon: 'it',
        cities: ['Rome', 'Milan', 'Naples', 'Turin'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1003,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '25',
        name: 'Japan',
        alpha2Code: 'jp',
        alpha3Code: 'jpn',
        numericCode: '392',
        callingCode: '81',
        icon: 'jp',
        cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2013,
        ipAvailiblePrivate: 48,
        ipAvailiblePrivateCities: [15, 20, 8, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '26',
        name: 'Kazakhstan',
        alpha2Code: 'kz',
        alpha3Code: 'kaz',
        numericCode: '398',
        callingCode: '7',
        icon: 'kz',
        cities: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 10, 5, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '27',
        name: 'Kenya',
        alpha2Code: 'ke',
        alpha3Code: 'ken',
        numericCode: '404',
        callingCode: '254',
        icon: 'ke',
        cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 20,
        ipAvailiblePrivateCities: [6, 8, 4, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '28',
        name: 'Latvia',
        alpha2Code: 'lv',
        alpha3Code: 'lva',
        numericCode: '428',
        callingCode: '371',
        icon: 'lv',
        cities: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [8, 7, 6, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '29',
        name: 'Luxembourg',
        alpha2Code: 'lu',
        alpha3Code: 'lux',
        numericCode: '442',
        callingCode: '352',
        icon: 'lu',
        cities: ['Luxembourg', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 36,
        ipAvailiblePrivateCities: [10, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '30',
        name: 'Malaysia',
        alpha2Code: 'my',
        alpha3Code: 'mys',
        numericCode: '458',
        callingCode: '60',
        icon: 'my',
        cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '31',
        name: 'Mexico',
        alpha2Code: 'mx',
        alpha3Code: 'mex',
        numericCode: '484',
        callingCode: '52',
        icon: 'mx',
        cities: ['Mexico City', 'Ecatepec', 'Guadalajara', 'Puebla'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 15,
        ipAvailiblePrivateCities: [5, 4, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '32',
        name: 'Netherlands',
        alpha2Code: 'nl',
        alpha3Code: 'nld',
        numericCode: '528',
        callingCode: '31',
        icon: 'nl',
        cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1018,
        ipAvailiblePrivate: 42,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '33',
        name: 'New Zealand',
        alpha2Code: 'nz',
        alpha3Code: 'nzl',
        numericCode: '554',
        callingCode: '64',
        icon: 'nz',
        cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '34',
        name: 'Norway',
        alpha2Code: 'no',
        alpha3Code: 'nor',
        numericCode: '578',
        callingCode: '47',
        icon: 'no',
        cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 62,
        ipAvailiblePrivateCities: [20, 20, 12, 10],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '35',
        name: 'Poland',
        alpha2Code: 'pl',
        alpha3Code: 'pol',
        numericCode: '616',
        callingCode: '48',
        icon: 'pl',
        cities: ['Warsaw', 'Krakow', 'Lodz', 'Wroclaw'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [6, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '36',
        name: 'Portugal',
        alpha2Code: 'pt',
        alpha3Code: 'prt',
        numericCode: '620',
        callingCode: '351',
        icon: 'pt',
        cities: ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: ' disabled',
        ipAvailibleShared: 756,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '37',
        name: 'Republic of Korea',
        alpha2Code: 'kr',
        alpha3Code: 'kor',
        numericCode: '410',
        callingCode: '82',
        icon: 'kr',
        cities: ['Seoul', 'Busan', 'Incheon', 'Daegu'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '38',
        name: 'Republic of Lithuania',
        alpha2Code: 'lt',
        alpha3Code: 'ltu',
        numericCode: '440',
        callingCode: '370',
        icon: 'lt',
        cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '39',
        name: 'Republic of Moldova',
        alpha2Code: 'md',
        alpha3Code: 'mda',
        numericCode: '498',
        callingCode: '373',
        icon: 'md',
        cities: ['Chisinau', 'Tiraspol', 'Balti', 'Bender'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 55,
        ipAvailiblePrivateCities: [17, 20, 10, 8],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '40',
        name: 'Romania',
        alpha2Code: 'ro',
        alpha3Code: 'rou',
        numericCode: '642',
        callingCode: '40',
        icon: 'ro',
        cities: ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 27,
        ipAvailiblePrivateCities: [8, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '41',
        name: 'Russia',
        alpha2Code: 'ru',
        alpha3Code: 'rus',
        numericCode: '643',
        callingCode: '7',
        icon: 'ru',
        cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 2120,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '42',
        name: 'Singapore',
        alpha2Code: 'sg',
        alpha3Code: 'sgp',
        numericCode: '702',
        callingCode: '65',
        icon: 'sg',
        cities: ['Singapore', 'Woodlands', 'Jurong East', 'Tampines'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 81,
        ipAvailiblePrivateCities: [25, 30, 15, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '44',
        name: 'Slovakia',
        alpha2Code: 'sk',
        alpha3Code: 'svk',
        numericCode: '703',
        callingCode: '421',
        icon: 'sk',
        cities: ['Bratislava', 'Kosice', 'Presov', 'Nitra'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 18,
        ipAvailiblePrivateCities: [5, 6, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '45',
        name: 'South Africa',
        alpha2Code: 'za',
        alpha3Code: 'zaf',
        numericCode: '710',
        callingCode: '27',
        icon: 'za',
        cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 856,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '46',
        name: 'Spain',
        alpha2Code: 'es',
        alpha3Code: 'esp',
        numericCode: '724',
        callingCode: '34',
        icon: 'es',
        cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '47',
        name: 'Sweden',
        alpha2Code: 'se',
        alpha3Code: 'swe',
        numericCode: '752',
        callingCode: '46',
        icon: 'se',
        cities: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '48',
        name: 'Switzerland',
        alpha2Code: 'ch',
        alpha3Code: 'che',
        numericCode: '756',
        callingCode: '41',
        icon: 'ch',
        cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '49',
        name: 'Thailand',
        alpha2Code: 'th',
        alpha3Code: 'tha',
        numericCode: '764',
        callingCode: '66',
        icon: 'th',
        cities: ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 28,
        ipAvailiblePrivateCities: [9, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [9, 45, 90],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '50',
        name: 'Turkey',
        alpha2Code: 'tr',
        alpha3Code: 'tur',
        numericCode: '792',
        callingCode: '90',
        icon: 'tr',
        cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1031,
        ipAvailiblePrivate: 24,
        ipAvailiblePrivateCities: [7, 9, 5, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '51',
        name: 'Ukraine',
        alpha2Code: 'ua',
        alpha3Code: 'ukr',
        numericCode: '804',
        callingCode: '380',
        icon: 'ua',
        cities: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1021,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '52',
        name: 'United Arab Emirates',
        alpha2Code: 'ae',
        alpha3Code: 'are',
        numericCode: '784',
        callingCode: '971',
        icon: 'ae',
        cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1045,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '53',
        name: 'Vietnam',
        alpha2Code: 'vn',
        alpha3Code: 'vnm',
        numericCode: '704',
        callingCode: '84',
        icon: 'vn',
        cities: ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Da Nang'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 18,
        ipAvailiblePrivateCities: [5, 6, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '54',
        name: 'Uzbekistan',
        alpha2Code: 'uz',
        alpha3Code: 'uzb',
        numericCode: '860',
        callingCode: '998',
        icon: 'uz',
        cities: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '55',
        name: 'Saudi Arabia',
        alpha2Code: 'sa',
        alpha3Code: 'sau',
        numericCode: '682',
        callingCode: '966',
        icon: 'sa',
        cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 1004,
        ipAvailiblePrivate: 20,
        ipAvailiblePrivateCities: [6, 8, 4, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '56',
        name: 'Serbia',
        alpha2Code: 'rs',
        alpha3Code: 'srb',
        numericCode: '688',
        callingCode: '381',
        icon: 'rs',
        cities: ['Belgrade', 'Novi Sad', 'Nis', 'Zemun'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 21,
        ipAvailiblePrivateCities: [6, 8, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '57',
        name: 'Sri Lanka',
        alpha2Code: 'lk',
        alpha3Code: 'lka',
        numericCode: '144',
        callingCode: '94',
        icon: 'lk',
        cities: ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Negombo'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 14,
        ipAvailiblePrivateCities: [4, 5, 2, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '58',
        name: 'Tunisia',
        alpha2Code: 'tn',
        alpha3Code: 'tun',
        numericCode: '788',
        callingCode: '216',
        icon: 'tn',
        cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '59',
        name: 'Qatar',
        alpha2Code: 'qa',
        alpha3Code: 'qat',
        numericCode: '634',
        callingCode: '974',
        icon: 'qa',
        cities: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'],
        isPrivate: true,
        isShared: true,
        sharedClass: ' shared',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 987,
        ipAvailiblePrivate: 24,
        ipAvailiblePrivateCities: [7, 9, 4, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '60',
        name: 'Philippines',
        alpha2Code: 'ph',
        alpha3Code: 'phl',
        numericCode: '608',
        callingCode: '63',
        icon: 'ph',
        cities: ['Quezon City', 'Manila', 'Davao City', 'Caloocan'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 15,
        ipAvailiblePrivateCities: [5, 4, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '61',
        name: 'Pakistan',
        alpha2Code: 'pk',
        alpha3Code: 'pak',
        numericCode: '586',
        callingCode: '92',
        icon: 'pk',
        cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi'],
        isPrivate: true,
        isShared: false,
        sharedClass: '',
        privateClass: ' private',
        disabledClass: '',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
    ];
  }
  constructor() {}
}
