import { Injectable } from '@angular/core';
import { CountryProxy } from '../interfaces/country-proxy';

@Injectable({
  providedIn: 'root'
})
export class CountriesProxyService {
  getCountries(): CountryProxy[] {
    return [
      {
        id: '1',
        name: 'United States',
        code: 'us',
        flag: 'us',
        cities: ['New York', 'Los Angeles', 'Nevada', 'Illinois'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 20496,
        ipAvailiblePrivate: 277,
        ipAvailiblePrivateCities: [27, 47, 97, 47],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '2',
        name: 'United Kingdom',
        code: 'uk',
        flag: 'uk',
        cities: ['London', 'Manchester', 'Liverpool', 'Birmingham'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 70,
        ipAvailiblePrivateCities: [10, 23, 30, 14],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '3',
        name: 'Germany',
        code: 'de',
        flag: 'de',
        cities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 2022,
        ipAvailiblePrivate: 86,
        ipAvailiblePrivateCities: [20, 30, 20, 16],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '4',
        name: 'France',
        code: 'fr',
        flag: 'fr',
        cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 46,
        ipAvailiblePrivateCities: [19, 25, 41, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 30, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '5',
        name: 'Canada',
        code: 'ca',
        flag: 'ca',
        cities: ['Toronto', 'Montreal', 'Vancouver', 'Ottawa'],
        shared: ' Shared',
        private: ' Private',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [16, 25, 28, 15],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '6',
        name: 'Albania',
        code: 'al',
        flag: 'al',
        cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 1020,
        ipAvailiblePrivate: 85,
        ipAvailiblePrivateCities: [26, 15, 21, 23],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '7',
        name: 'Australia',
        code: 'au',
        flag: 'au',
        cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
        shared: '',
        private: ' Private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 15, 5, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '8',
        name: 'Austria',
        code: 'at',
        flag: 'at',
        cities: ['Vienna', 'Graz', 'Linz', 'Salzburg'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [14, 11, 9, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '9',
        name: 'Belarus',
        code: 'by',
        flag: 'by',
        cities: ['Minsk', 'Gomel', 'Mogilev', 'Brest'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '10',
        name: 'Bosna and Herzegovina',
        code: 'ba',
        flag: 'ba',
        cities: ['Sarajevo', 'Banja Luka', 'Zenica', 'Tuzla'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [2, 7, 4, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '11',
        name: 'Brazil',
        code: 'br',
        flag: 'br',
        cities: ['Sao Paulo', 'Rio de Janeiro', 'Salvador', 'Brasilia'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 39,
        ipAvailiblePrivateCities: [13, 19, 8, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 50, 100],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '12',
        name: 'Bulgaria',
        code: 'bg',
        flag: 'bg',
        cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 13,
        ipAvailiblePrivateCities: [4, 5, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '13',
        name: 'Cyprus',
        code: 'cy',
        flag: 'cy',
        cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '14',
        name: 'Czech Republic',
        code: 'cz',
        flag: 'cz',
        cities: ['Prague', 'Brno', 'Ostrava', 'Plzen'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      }
      {
        id: '15',
        name: 'Egypt',
        code: 'eg',
        flag: 'eg',
        cities: ['Cairo', 'Alexandria', 'Giza', 'Ash-Sharqia'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 35,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      }
      {
        id: '16',
        name: 'Estonia',
        code: 'ee',
        flag: 'ee',
        cities: ['Tallinn', 'Tartu', 'Narva', 'Parnu'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 34,
        ipAvailiblePrivateCities: [10, 7, 13, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      }
      {
        id: '17',
        name: 'Finland',
        code: 'fi',
        flag: 'fi',
        cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 6, 8, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      }
      {
        id: '18',
        name: 'Greece',
        code: 'gr',
        flag: 'gr',
        cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 6,
        ipAvailiblePrivateCities: [2, 1, 3, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '19',
        name: 'Hong Kong',
        code: 'hk',
        flag: 'hk',
        cities: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '20',
        name: 'Hungary',
        code: 'hu',
        flag: 'hu',
        cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 11,
        ipAvailiblePrivateCities: [4, 3, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '21',
        name: 'India',
        code: 'in',
        flag: 'in',
        cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '22',
        name: 'Ireland',
        code: 'ie',
        flag: 'ie',
        cities: ['Dublin', 'Cork', 'Limerick', 'Galway'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '23',
        name: 'Palestine',
        code: 'ps',
        flag: 'ps',
        cities: ['Gaza', 'Jerusalem', 'Nablus', 'Rafah'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [3, 15, 30],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '24',
        name: 'Italy',
        code: 'it',
        flag: 'it',
        cities: ['Rome', 'Milan', 'Naples', 'Turin'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1003,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '25',
        name: 'Japan',
        code: 'jp',
        flag: 'jp',
        cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 48,
        ipAvailiblePrivateCities: [15, 20, 8, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '26',
        name: 'Kazakhstan',
        code: 'kz',
        flag: 'kz',
        cities: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 26,
        ipAvailiblePrivateCities: [8, 10, 5, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '27',
        name: 'Kenya',
        code: 'ke',
        flag: 'ke',
        cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 20,
        ipAvailiblePrivateCities: [6, 8, 4, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '28',
        name: 'Latvia',
        code: 'lv',
        flag: 'lv',
        cities: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 25,
        ipAvailiblePrivateCities: [8, 7, 6, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '29',
        name: 'Luxembourg',
        code: 'lu',
        flag: 'lu',
        cities: ['Luxembourg', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 36,
        ipAvailiblePrivateCities: [10, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '30',
        name: 'Malaysia',
        code: 'my',
        flag: 'my',
        cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '31',
        name: 'Mexico',
        code: 'mx',
        flag: 'mx',
        cities: ['Mexico City', 'Ecatepec', 'Guadalajara', 'Puebla'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 15,
        ipAvailiblePrivateCities: [5, 4, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '32',
        name: 'Netherlands',
        code: 'nl',
        flag: 'nl',
        cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1018,
        ipAvailiblePrivate: 42,
        ipAvailiblePrivateCities: [10, 7, 13, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '33',
        name: 'New Zealand',
        code: 'nz',
        flag: 'nz',
        cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 9,
        ipAvailiblePrivateCities: [3, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '34',
        name: 'Norway',
        code: 'no',
        flag: 'no',
        cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 62,
        ipAvailiblePrivateCities: [20, 20, 12, 10],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '35',
        name: 'Poland',
        code: 'pl',
        flag: 'pl',
        cities: ['Warsaw', 'Krakow', 'Lodz', 'Wroclaw'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 17,
        ipAvailiblePrivateCities: [6, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '36',
        name: 'Portugal',
        code: 'pt',
        flag: 'pt',
        cities: ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id:'37',
        name: 'Republic of Korea',
        code: 'kr',
        flag: 'kr',
        cities: ['Seoul', 'Busan', 'Incheon', 'Daegu'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '38',
        name: 'Republic of Lithuania',
        code: 'lt',
        flag: 'lt',
        cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 5,
        ipAvailiblePrivateCities: [2, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '39',
        name: 'Republic of Moldova',
        code: 'md',
        flag: 'md',
        cities: ['Chisinau', 'Tiraspol', 'Balti', 'Bender'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 55,
        ipAvailiblePrivateCities: [17, 20, 10, 8],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '40',
        name: 'Romania',
        code: 'ro',
        flag: 'ro',
        cities: ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 27,
        ipAvailiblePrivateCities: [8, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '41',
        name: 'Russia',
        code: 'ru',
        flag: 'ru',
        cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 2120,
        ipAvailiblePrivate: 4,
        ipAvailiblePrivateCities: [1, 1, 1, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '42',
        name: 'Singapore',
        code: 'sg',
        flag: 'sg',
        cities: ['Singapore', 'Woodlands', 'Jurong East', 'Tampines'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 81,
        ipAvailiblePrivateCities: [25, 30, 15, 11],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '44',
        name: 'Slovakia',
        code: 'sk',
        flag: 'sk',
        cities: ['Bratislava', 'Kosice', 'Presov', 'Nitra'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 18,
        ipAvailiblePrivateCities: [5, 6, 4, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [8, 40, 80],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '45',
        name: 'South Africa',
        code: 'za',
        flag: 'za',
        cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 29, 49],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '46',
        name: 'Spain',
        code: 'es',
        flag: 'es',
        cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1010,
        ipAvailiblePrivate: 12,
        ipAvailiblePrivateCities: [4, 4, 2, 2],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '47',
        name: 'Sweden',
        code: 'se',
        flag: 'se',
        cities: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala'],
        shared: ' shared',
        private: ' private',
        ipAvailibleShared: 1011,
        ipAvailiblePrivate: 38,
        ipAvailiblePrivateCities: [12, 15, 6, 5],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [6, 30, 60],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '48',
        name: 'Switzerland',
        code: 'ch',
        flag: 'ch',
        cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 16,
        ipAvailiblePrivateCities: [5, 5, 3, 3],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '49',
        name: 'Thailand',
        code: 'th',
        flag: 'th',
        cities: ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 28,
        ipAvailiblePrivateCities: [9, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [9, 45, 90],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '50',
        name: 'Turkey',
        code: 'tr',
        flag: 'tr',
        cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [9, 10, 5, 4],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '51',
        name: 'Ukraine',
        code: 'ua',
        flag: 'ua',
        cities: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 1021,
        ipAvailiblePrivate: 67,
        ipAvailiblePrivateCities: [20, 25, 15, 7],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [5, 25, 50],
        priceWithDiscount: 0,
        discount: 0,
      },
      {
        id: '52',
        name: 'United Arab Emirates',
        code: 'ae',
        flag: 'ae',
        cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'],
        shared: '',
        private: ' private',
        ipAvailibleShared: 0,
        ipAvailiblePrivate: 8,
        ipAvailiblePrivateCities: [2, 3, 2, 1],
        priceShared: [0.2, 0.4, 2],
        pricePrivate: [7, 35, 70],
        priceWithDiscount: 0,
        discount: 0,
      },
    ];
  }
  constructor() { }
}
